// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from '@prisma/client';

export default defineConfig({
  migrations: {
    path: "prisma/migrations",
  },
  datasourceUrl: 'mysql://root:@localhost:3306/kolleksi-dolan-manut',
});
